# Generated by Django 4.1.2 on 2022-10-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_alter_purpleusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpleusers',
            name='image',
            field=models.ImageField(blank=True, default='generic_user.jpg', upload_to='img'),
        ),
    ]
