# Generated by Django 4.1.2 on 2022-10-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0003_alter_purpleusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpleusers',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
