# Generated by Django 4.1.2 on 2022-11-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0006_alter_purpleusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpleusers',
            name='image',
            field=models.ImageField(blank=True, default='profiles/generic_user.jpg', upload_to='profiles/'),
        ),
    ]
